// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: smn_base.proto

package smn_base

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Call struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dict int32  `protobuf:"varint,1,opt,name=dict,proto3" json:"dict,omitempty"`
	Msg  []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Call) Reset() {
	*x = Call{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smn_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_smn_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_smn_base_proto_rawDescGZIP(), []int{0}
}

func (x *Call) GetDict() int32 {
	if x != nil {
		return x.Dict
	}
	return 0
}

func (x *Call) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type Ret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dict int32  `protobuf:"varint,1,opt,name=dict,proto3" json:"dict,omitempty"`
	Err  bool   `protobuf:"varint,2,opt,name=Err,proto3" json:"Err,omitempty"`
	Msg  []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Ret) Reset() {
	*x = Ret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smn_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ret) ProtoMessage() {}

func (x *Ret) ProtoReflect() protoreflect.Message {
	mi := &file_smn_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ret.ProtoReflect.Descriptor instead.
func (*Ret) Descriptor() ([]byte, []int) {
	return file_smn_base_proto_rawDescGZIP(), []int{1}
}

func (x *Ret) GetDict() int32 {
	if x != nil {
		return x.Dict
	}
	return 0
}

func (x *Ret) GetErr() bool {
	if x != nil {
		return x.Err
	}
	return false
}

func (x *Ret) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type FPkg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NO  int64  `protobuf:"varint,1,opt,name=NO,proto3" json:"NO,omitempty"`
	Msg []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Err bool   `protobuf:"varint,3,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *FPkg) Reset() {
	*x = FPkg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smn_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FPkg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FPkg) ProtoMessage() {}

func (x *FPkg) ProtoReflect() protoreflect.Message {
	mi := &file_smn_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FPkg.ProtoReflect.Descriptor instead.
func (*FPkg) Descriptor() ([]byte, []int) {
	return file_smn_base_proto_rawDescGZIP(), []int{2}
}

func (x *FPkg) GetNO() int64 {
	if x != nil {
		return x.NO
	}
	return 0
}

func (x *FPkg) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *FPkg) GetErr() bool {
	if x != nil {
		return x.Err
	}
	return false
}

var File_smn_base_proto protoreflect.FileDescriptor

var file_smn_base_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x6d, 0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x6d, 0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x04, 0x43, 0x61,
	0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x64, 0x69, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3d, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x69, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64,
	0x69, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x45, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3a, 0x0a, 0x04, 0x46, 0x50, 0x6b, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x4e, 0x4f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x4e, 0x4f, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03,
	0x45, 0x72, 0x72, 0x42, 0x43, 0x0a, 0x02, 0x70, 0x62, 0x42, 0x08, 0x73, 0x6d, 0x6e, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x73, 0x47, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x73, 0x6d,
	0x6e, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x73, 0x6d, 0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x3b,
	0x73, 0x6d, 0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smn_base_proto_rawDescOnce sync.Once
	file_smn_base_proto_rawDescData = file_smn_base_proto_rawDesc
)

func file_smn_base_proto_rawDescGZIP() []byte {
	file_smn_base_proto_rawDescOnce.Do(func() {
		file_smn_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_smn_base_proto_rawDescData)
	})
	return file_smn_base_proto_rawDescData
}

var file_smn_base_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_smn_base_proto_goTypes = []interface{}{
	(*Call)(nil), // 0: smn_base.Call
	(*Ret)(nil),  // 1: smn_base.Ret
	(*FPkg)(nil), // 2: smn_base.FPkg
}
var file_smn_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smn_base_proto_init() }
func file_smn_base_proto_init() {
	if File_smn_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smn_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Call); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smn_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smn_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FPkg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smn_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smn_base_proto_goTypes,
		DependencyIndexes: file_smn_base_proto_depIdxs,
		MessageInfos:      file_smn_base_proto_msgTypes,
	}.Build()
	File_smn_base_proto = out.File
	file_smn_base_proto_rawDesc = nil
	file_smn_base_proto_goTypes = nil
	file_smn_base_proto_depIdxs = nil
}
